language: go

go:
  - "1.9"

install:
  - go get -v github.com/alecthomas/gometalinter
  - gometalinter --install
  - go get -v

script:
  - gometalinter --aggregate --vendor --exclude="zz_generated" --enable-all --disable=gas --disable=gotype --disable=lll --disable=safesql --disable=varcheck --deadline=600s --exclude=vendor ./...
  - go test $(go list ./... | grep -v /vendor/)
  - go build
