language: go

go:
  - "1.8"

before_install:
  - go get -v github.com/alecthomas/gometalinter
  - go install github.com/alecthomas/gometalinter

script:
  - gometalinter --aggregate --vendor --exclude="zz_generated" --enable-all --disable=gas --disable=gotype --disable=lll --disable=safesql --deadline=600s ./...
  - go test -v ./...
