language: go

go:
  - "1.8"

install:
  - go get -v github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - gometalinter --aggregate --vendor --exclude="zz_generated" --enable-all --disable=gas --disable=gotype --disable=lll --disable=safesql --deadline=600s ./...
  - go test -v ./...
